apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vortex-framework-features.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vortex-framework-features.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vortex-framework-features.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vortex-framework-features.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.disableServiceAccountName }}
      serviceAccountName: {{ include "vortex-framework-features.serviceAccountName" . }}
      {{- end }}
      {{- if not .Values.disableSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if not .Values.disableSecurityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: vortex-framework-config
          volumeMounts:
          - mountPath: /authcreds
            name: auth-creds-vol
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Values.configMapToLoadAsAuthCreds }}
        name: auth-creds-vol
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
